// import { BloodPressureDetail } from '../../patients/model/response-model/blood-pressure-detail';

const bloodPressureDetail = {
    result: {
        code: '0',
        message: 'ok',
    },
    contract_application: 1,
    row_data: [
        {
            date_time: '01/01/2020 21:30',
            input_type: 1,
            sys: 180,
            dia: 92,
            pulse: 92,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '01/02/2020',
            input_type: 1,
            sys: 186,
            dia: 92,
            pulse: 90,
            meas_state: [1, 2]
        },
        {
            date_time: '01/03/2020 06:20',
            input_type: 2,
            sys: 183,
            dia: 78,
            pulse: 93,
            meas_state: [2, 3]
        },
        {
            date_time: '1/04/2020',
            input_type: 2,
            sys: 185,
            dia: 82,
            pulse: 90,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/05/2020 20:00',
            input_type: 3,
            sys: 187,
            dia: 93,
            pulse: 92,
            meas_state: [1, 3],
        },
        {
            date_time: '1/06/2020 07:00',
            input_type: 3,
            sys: 186,
            dia: 92,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/06/2020 09:00',
            input_type: 3,
            sys: 176,
            dia: 94,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/07/2020 13:00',
            input_type: 3,
            sys: 185,
            dia: 12,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/08/2020 16:1',
            input_type: 2,
            sys: 193,
            dia: 10,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/09/2020 08:00',
            input_type: 2,
            sys: 189,
            dia: 10,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/10/2020 1:00',
            input_type: 2,
            sys: 185,
            dia: 95,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/11/2020 13:21',
            input_type: 3,
            sys: 186,
            dia: 92,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/12/2020 22:00',
            input_type: 3,
            sys: 186,
            dia: 92,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/13/2020 23:00',
            input_type: 3,
            sys: 186,
            dia: 92,
            pulse: 91,
            meas_state: [1, 2, 3]
        },
        {
            date_time: '1/14/2020 07:00',
            input_type: 3,
            sys: 186,
            dia: 92,
            pulse: 91,
            meas_state: [1, 2, 3]
        }

    ],
    daily_data: [
        {
            date: '1/01/2020',
            rank_total: 1,
            sys_avg_day: 178,
            dia_avg_day: 90,
            avg_pluse: 96,
            meas_state_day: [1, 2, 3],
            side_effects: [1, 2, 3, 4, 5, 6]
        },
        {
            date: '1/02/2020',
            rank_total: 2,
            sys_avg_day: 190,
            dia_avg_day: 101,
            avg_pluse: 88,
            meas_state_day: [2, 3],
            side_effects: [1, 2, 5, 6]
        },
        {
            date: '1/03/2020',
            rank_total: 3,
            sys_avg_day: 186,
            dia_avg_day: 93,
            avg_pluse: 96,
            meas_state_day: [1, 2, 3],
            side_effects: [3, 4, 5, 6]
        },
        {
            date: '1/04/2020',
            rank_total: 1,
            sys_avg_day: 193,
            dia_avg_day: 13,
            avg_pluse: 96,
            meas_state_day: [1, 2, 3],
            side_effects: [1, 2, 3, 4,]
        },
        {
            date: '1/05/2020',
            rank_total: 1,
            sys_avg_day: 188,
            dia_avg_day: 90,
            avg_pluse: 96,
            meas_state_day: [1, 2, 3],
            side_effects: [1, 2, 3, 4, 5, 6]
        },
        {
            date: '1/06/2020',
            rank_total: 1,
            sys_avg_day: 186,
            dia_avg_day: 90,
            avg_pluse: 96,
            meas_state_day: [1, 2, 3],
            side_effects: [1, 2, 3, 4, 5, 6]
        },
        {
            date: '1/07/2020',
            rank_total: 1,
            sys_avg_day: 178,
            dia_avg_day: 90,
            avg_pluse: 88,
            meas_state_day: [1, 2, 3],
            side_effects: [1, 2, 3, 4, 5, 6]
        },
        {
            date: '1/08/2020',
            rank_total: 4,
            sys_avg_day: 188,
            dia_avg_day: 93,
            avg_pluse: 96,
            meas_state_day: [1, 2],
            side_effects: [1, 2, 3, 4, 5, 6]
        },
        {
            date: '1/09/2020',
            rank_total: 2,
            sys_avg_day: 192,
            dia_avg_day: 90,
            avg_pluse: 97,
            meas_state_day: [1, 3],
            side_effects: [1, 2, 3, 4, 5, 6]
        },
        {
            date: '1/10/2020',
            rank_total: 1,
            sys_avg_day: 178,
            dia_avg_day: 90,
            avg_pluse: 96,
            meas_state_day: [],
            side_effects: [1, 2, 3, 6]
        },
        {
            date: '1/11/2020',
            rank_total: 1,
            sys_avg_day: 188,
            dia_avg_day: 93,
            avg_pluse: 95,
            meas_state_day: [1, 2],
            side_effects: [3, 4, 5, 6]
        },
        {
            date: '1/12/2020',
            rank_total: 1,
            sys_avg_day: 183,
            dia_avg_day: 97,
            avg_pluse: 98,
            meas_state_day: [1, 2, 3],
            side_effects: [1, 2, 3, 4, 5, 6]
        },
        {
            date: '1/13/2020',
            rank_total: 1,
            sys_avg_day: 180,
            dia_avg_day: 92,
            avg_pluse: 86,
            meas_state_day: [1, 2, 3],
            side_effects: [1, 2, 3, 4, 5, 6]
        },
    ],
    graph_data: [
        {
            date: '01/01/2020',
            rank_total: 3,
            sys_avg_evening: 135,
            sys_avg_morning: 130,
            pulse_avg_evening: 77,
            pulse_avg_morning: 72,
            dia_avg_evening: 85,
            dia_avg_morning: 87,
            dia_avg_office: 86,
            side_effects: [1, 2, 3, 4, 5, 6],
            ihb_count: 150,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 134,
            pulse_avg_office: 80,
            take: 0
        },
        {
            date: '01/02/2020',
            rank_total: 3,
            sys_avg_evening: 132,
            sys_avg_morning: 128,
            pulse_avg_evening: 79,
            pulse_avg_morning: 70,
            dia_avg_evening: 100,
            dia_avg_morning: 96,
            dia_avg_office: 95,
            side_effects: [1, 2, 3, 4, 5, 6],
            ihb_count: 160,
            meas_state: 1,
            meas_state_morning: [],
            meas_state_evening: [],
            sys_avg_office: 133,
            pulse_avg_office: 72,
            take: 0
        },
        {
            date: '01/03/2020',
            rank_total: 2,
            sys_avg_evening: 128,
            sys_avg_morning: 130,
            pulse_avg_evening: 73,
            pulse_avg_morning: 79,
            dia_avg_evening: 92,
            dia_avg_morning: 95,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 163,
            meas_state: 1,
            meas_state_morning: [1, 3],
            meas_state_evening: [1, 2],
            sys_avg_office: 133,
            pulse_avg_office: 72,
            take: 1
        },
        {
            date: '01/04/2020',
            rank_total: 1,
            sys_avg_evening: 115,
            sys_avg_morning: 120,
            pulse_avg_evening: 70,
            pulse_avg_morning: 71,
            dia_avg_evening: 92,
            dia_avg_morning: 93,
            dia_avg_office: 97,
            side_effects: [1, 2, 3],
            ihb_count: 153,
            meas_state: 1,
            meas_state_morning: [],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 125,
            pulse_avg_office: 70,
            take: 1
        },
        {
            date: '01/05/2020',
            rank_total: 2,
            sys_avg_evening: 133,
            sys_avg_morning: 130,
            pulse_avg_evening: 72,
            pulse_avg_morning: 70,
            dia_avg_evening: 100,
            dia_avg_morning: 103,
            dia_avg_office: 95,
            side_effects: [],
            ihb_count: 143,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [],
            sys_avg_office: 129,
            pulse_avg_office: 77,
            take: 0
        },
        {
            date: '01/06/2020',
            rank_total: 0,
            sys_avg_evening: 129,
            sys_avg_morning: 133,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 98,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 165,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 125,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/07/2020',
            rank_total: 3,
            sys_avg_evening: 127,
            sys_avg_morning: 133,
            pulse_avg_evening: 77,
            pulse_avg_morning: 78,
            dia_avg_evening: 103,
            dia_avg_morning: 97,
            dia_avg_office: 90,
            side_effects: [1, 2, 3],
            ihb_count: 175,
            meas_state: 1,
            meas_state_morning: [],
            meas_state_evening: [],
            sys_avg_office: 135,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/08/2020',
            rank_total: 3,
            sys_avg_evening: 125,
            sys_avg_morning: 135,
            pulse_avg_evening: 70,
            pulse_avg_morning: 75,
            dia_avg_evening: 75,
            dia_avg_morning: 85,
            dia_avg_office: 96,
            side_effects: [1, 2, 3, 4, 5, 6],
            ihb_count: 132,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 133,
            pulse_avg_office: 78,
            take: 1
        },
        {
            date: '01/09/2020',
            rank_total: 3,
            sys_avg_evening: 133,
            sys_avg_morning: 120,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 98,
            dia_avg_morning: 105,
            dia_avg_office: 93,
            side_effects: [1, 2, 3],
            ihb_count: 150,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 125,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/10/2020',
            rank_total: 3,
            sys_avg_evening: 129,
            sys_avg_morning: 133,
            pulse_avg_evening: 70,
            pulse_avg_morning: 70,
            dia_avg_evening: 102,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 144,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 129,
            pulse_avg_office: 70,
            take: 0
        },
        {
            date: '01/11/2020',
            rank_total: 3,
            sys_avg_evening: 135,
            sys_avg_morning: 125,
            pulse_avg_evening: 76,
            pulse_avg_morning: 79,
            dia_avg_evening: 98,
            dia_avg_morning: 95,
            dia_avg_office: 106,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 70,
            take: 0
        },
        {
            date: '01/12/2020',
            rank_total: 3,
            sys_avg_evening: 127,
            sys_avg_morning: 122,
            pulse_avg_evening: 78,
            pulse_avg_morning: 76,
            dia_avg_evening: 101,
            dia_avg_morning: 103,
            dia_avg_office: 85,
            side_effects: [1, 2, 3],
            ihb_count: 150,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 134,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/13/2020',
            rank_total: 3,
            sys_avg_evening: 128,
            sys_avg_morning: 127,
            pulse_avg_evening: 76,
            pulse_avg_morning: 70,
            dia_avg_evening: 95,
            dia_avg_morning: 100,
            dia_avg_office: 105,
            side_effects: [1, 2, 3],
            ihb_count: 160,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 128,
            pulse_avg_office: 70,
            take: 0
        },
        {
            date: '01/14/2020',
            rank_total: 2,
            sys_avg_evening: 129,
            sys_avg_morning: 125,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 100,
            dia_avg_morning: 95,
            dia_avg_office: 105,
            side_effects: [1, 2, 3],
            ihb_count: 163,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 122,
            pulse_avg_office: 76,
            take: 1
        },
        {
            date: '01/15/2020',
            rank_total: 3,
            sys_avg_evening: 133,
            sys_avg_morning: 128,
            pulse_avg_evening: 76,
            pulse_avg_morning: 70,
            dia_avg_evening: 92,
            dia_avg_morning: 90,
            dia_avg_office: 97,
            side_effects: [1, 2, 3],
            ihb_count: 153,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 122,
            pulse_avg_office: 76,
            take: 0
        },
        {
            date: '01/16/2020',
            rank_total: 3,
            sys_avg_evening: 135,
            sys_avg_morning: 130,
            pulse_avg_evening: 80,
            pulse_avg_morning: 72,
            dia_avg_evening: 90,
            dia_avg_morning: 94,
            dia_avg_office: 85,
            side_effects: [1, 2, 3],
            ihb_count: 143,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 125,
            pulse_avg_office: 76,
            take: 0
        },
        {
            date: '01/17/2020',
            rank_total: 3,
            sys_avg_evening: 125,
            sys_avg_morning: 133,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 85,
            dia_avg_morning: 97,
            dia_avg_office: 92,
            side_effects: [1, 2, 3],
            ihb_count: 165,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 125,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/18/2020',
            rank_total: 3,
            sys_avg_evening: 128,
            sys_avg_morning: 133,
            pulse_avg_evening: 75,
            pulse_avg_morning: 70,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 102,
            side_effects: [1, 2, 3],
            ihb_count: 175,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 122,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/19/2020',
            rank_total: 3,
            sys_avg_evening: 122,
            sys_avg_morning: 133,
            pulse_avg_evening: 76,
            pulse_avg_morning: 70,
            dia_avg_evening: 90,
            dia_avg_morning: 95,
            dia_avg_office: 100,
            side_effects: [1, 2, 3],
            ihb_count: 132,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/20/2020',
            rank_total: 3,
            sys_avg_evening: 130,
            sys_avg_morning: 125,
            pulse_avg_evening: 78,
            pulse_avg_morning: 77,
            dia_avg_evening: 90,
            dia_avg_morning: 95,
            dia_avg_office: 100,
            side_effects: [1, 2, 3],
            ihb_count: 132,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 122,
            pulse_avg_office: 72,
            take: 0
        },
        {
            date: '01/21/2020',
            rank_total: 3,
            sys_avg_evening: 129,
            sys_avg_morning: 133,
            pulse_avg_evening: 70,
            pulse_avg_morning: 76,
            dia_avg_evening: 95,
            dia_avg_morning: 90,
            dia_avg_office: 100,
            side_effects: [1, 2, 3],
            ihb_count: 144,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 125,
            pulse_avg_office: 78,
            take: 0
        },
        {
            date: '01/22/2020',
            rank_total: 3,
            sys_avg_evening: 133,
            sys_avg_morning: 123,
            pulse_avg_evening: 74,
            pulse_avg_morning: 77,
            dia_avg_evening: 93,
            dia_avg_morning: 95,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 122,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/23/2020',
            rank_total: 3,
            sys_avg_evening: 128,
            sys_avg_morning: 133,
            pulse_avg_evening: 75,
            pulse_avg_morning: 77,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 129,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '01/24/2020',
            rank_total: 3,
            sys_avg_evening: 130,
            sys_avg_morning: 128,
            pulse_avg_evening: 79,
            pulse_avg_morning: 73,
            dia_avg_evening: 98,
            dia_avg_morning: 102,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 122,
            pulse_avg_office: 80,
            take: 0
        },
        {
            date: '01/25/2020',
            rank_total: 3,
            sys_avg_evening: 131,
            sys_avg_morning: 125,
            pulse_avg_evening: 77,
            pulse_avg_morning: 79,
            dia_avg_evening: 95,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 129,
            pulse_avg_office: 70,
            take: 0
        },
        {
            date: '01/26/2020',
            rank_total: 3,
            sys_avg_evening: 126,
            sys_avg_morning: 133,
            pulse_avg_evening: 77,
            pulse_avg_morning: 73,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 102,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 126,
            pulse_avg_office: 78,
            take: 0
        },
        {
            date: '01/27/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 130,
            pulse_avg_evening: 75,
            pulse_avg_morning: 79,
            dia_avg_evening: 102,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 129,
            pulse_avg_office: 72,
            take: 0
        },
        {
            date: '01/28/2020',
            rank_total: 3,
            sys_avg_evening: 132,
            sys_avg_morning: 122,
            pulse_avg_evening: 75,
            pulse_avg_morning: 70,
            dia_avg_evening: 98,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 120,
            pulse_avg_office: 72,
            take: 0
        },
        {
            date: '01/29/2020',
            rank_total: 3,
            sys_avg_evening: 119,
            sys_avg_morning: 122,
            pulse_avg_evening: 78,
            pulse_avg_morning: 77,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 102,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 132,
            pulse_avg_office: 78,
            take: 0
        },
        {
            date: '01/30/2020',
            rank_total: 3,
            sys_avg_evening: 116,
            sys_avg_morning: 128,
            pulse_avg_evening: 76,
            pulse_avg_morning: 70,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 102,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 120,
            pulse_avg_office: 72,
            take: 0
        },
        {
            date: '01/31/2020',
            rank_total: 3,
            sys_avg_evening: 128,
            sys_avg_morning: 125,
            pulse_avg_evening: 75,
            pulse_avg_morning: 77,
            dia_avg_evening: 98,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 70,
            take: 0
        },
        {
            date: '02/01/2020',
            rank_total: 3,
            sys_avg_evening: 125,
            sys_avg_morning: 132,
            pulse_avg_evening: 78,
            pulse_avg_morning: 79,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 125,
            pulse_avg_office: 80,
            take: 0
        },
        {
            date: '02/02/2020',
            rank_total: 3,
            sys_avg_evening: 123,
            sys_avg_morning: 130,
            pulse_avg_evening: 80,
            pulse_avg_morning: 80,
            dia_avg_evening: 98,
            dia_avg_morning: 102,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 124,
            pulse_avg_office: 80,
            take: 0
        },
        {
            date: '02/03/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 131,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '02/04/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 131,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '02/05/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 131,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '02/06/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 131,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '02/07/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 131,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '02/08/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 131,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '02/09/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 131,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },
        {
            date: '02/10/2020',
            rank_total: 3,
            sys_avg_evening: 124,
            sys_avg_morning: 131,
            pulse_avg_evening: 75,
            pulse_avg_morning: 75,
            dia_avg_evening: 90,
            dia_avg_morning: 97,
            dia_avg_office: 99,
            side_effects: [1, 2, 3],
            ihb_count: 133,
            meas_state: 1,
            meas_state_morning: [1, 2, 3],
            meas_state_evening: [1, 2, 3],
            sys_avg_office: 130,
            pulse_avg_office: 75,
            take: 0
        },

    ],
    medicine_data: [
        {
            name: 'Fentanyl',
            quantity: '2',
            dosing_start: '01/01/2020',
            dosing_end: '01/30/2020'
        },
        {
            name: 'Haloperidol',
            quantity: '2',
            dosing_start: '01/01/2020',
            dosing_end: '01/15/2020',
            ingestion_start: '01/16/2020',
            ingestion_end: '01/30/2020'
        },
        {
            name: 'Ketamine',
            quantity: '2',
            dosing_start: '01/01/2020',
            dosing_end: '01/05/2020',
            ingestion_start: '01/06/2020',
            ingestion_end: '01/12/2020'
        },
        {
            name: 'Ketamine',
            quantity: '2',
            dosing_start: '01/13/2020',
            dosing_end: '01/18/2020',
            ingestion_start: '01/19/2020',
            ingestion_end: '01/25/2020'
        },
        {
            name: 'Ketamine',
            quantity: '2',
            dosing_start: '01/26/2020',
            dosing_end: '01/27/2020',
            ingestion_start: '01/28/2020',
            ingestion_end: '01/30/2020'
        },

        {
            name: 'Propofol',
            quantity: '2',
            dosing_start: '01/01/2020',
            dosing_end: '01/04/2020',
            ingestion_start: '01/05/2020',
            ingestion_end: '01/1/2020'
        },
        {
            name: 'Propofol',
            quantity: '2',
            dosing_start: '01/06/2020',
            dosing_end: '01/01/2020',
            ingestion_start: '01/1/2020',
            ingestion_end: '01/16/2020'
        },
        {
            name: 'Propofol',
            quantity: '2',
            dosing_start: '01/17/2020',
            dosing_end: '01/26/2020',
            ingestion_start: '01/27/2020',
            ingestion_end: '01/30/2020'
        },
        {
            name: 'Atropine',
            quantity: '2',
            dosing_start: '01/01/2020',
            dosing_end: '01/1/2020',
            ingestion_start: '01/11/2020',
            ingestion_end: '01/15/2020'
        },
        {
            name: 'Atropine',
            quantity: '2',
            dosing_start: '01/16/2020',
            dosing_end: '01/20/2020',
            ingestion_start: '01/22/2020',
            ingestion_end: '01/24/2020'
        },
        {
            name: 'Atropine',
            quantity: '2',
            dosing_start: '01/25/2020',
            dosing_end: '01/26/2020',
            ingestion_start: '01/27/2020',
            ingestion_end: '01/30/2020'
        },
        {
            name: 'Morphine',
            quantity: '2',
            dosing_start: '01/01/2020',
            dosing_end: '01/06/2020',
            ingestion_start: '01/07/2020',
            ingestion_end: '01/11/2020'
        },
        {
            name: 'Morphine',
            quantity: '2',
            dosing_start: '01/12/2020',
            dosing_end: '01/15/2020',
            ingestion_start: '01/16/2020',
            ingestion_end: '01/20/2020'
        },
        {
            name: 'Morphine',
            quantity: '2',
            dosing_start: '01/21/2020',
            dosing_end: '01/26/2020',
            ingestion_start: '01/27/2020',
            ingestion_end: '01/30/2020'
        }
    ]
}

console.log(bloodPressureDetail.row_data)

let startDate = new Date("2020-01-02");
let endDate = new Date("2022-3-25");
let aDate = new Date();

let filteredData = bloodPressureDetail.row_data.filter(function(item){
    let aDate = new Date(item.date_time);
    console.log(item.date_time);
    return aDate.getTime() >= startDate.getTime() && aDate.getTime() <= endDate.getTime();
});

console.log(filteredData)
// export default bloodPressureDetail;